name: LinkRelay
options:
  bundleIdPrefix: com.aoi
targets:
  LinkRelay:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: Resources
    info:
      path: Resources/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
